### ISSUE TITLE
Add cost tracking graph

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#415]
To facilitate the cost tracking graph we need to store the grade of the individual alongside their WLM. This will allow for people to change grades and keep historical data correct. We can choose to model the Max and Min costs by storing the salary costs alongside this too or we can just input them on the reference data page.

- [x] Update WLM to store grade
- [x] Select financial year
- [x] Recovery Target YTD (evenly spread through the weeks)
- [x] WLM-based Min and Max YTD (weekly based on WLMs and salary costs)
- [x] Reference values to be stored per FY in DB

**Comment by aharwood2** [comment]
Blocked by #332
