### ISSUE TITLE
Allow Innate codes to be "disabled" so no-longer show up in timesheet list

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#618]
It might be nothing to do with the timesheet code but the imported Innate code, thought I'd report it anyway:

When I tried to record my time spent on Research Connection Tool I can find two items in the Innate Code column:

- S-RES-RTP-14 - Research Connection Tool (Faroni)
- S-RES-P058 - Research Connection Tool (Faroni)

The data in that Innate code list may need to be cleaned.

**Tasks:**
- [x] Add disabled flag to the model
- [x] Add disabled field to the data grid
- [ ] Migration to disable all codes not attached to projects not cancelled or finished -- preserve the non-project codes

**Comment by aharwood2** [comment]
These will be here because someone at some point in the past has booked to it so it has to exist. I think this is really a need to be able to disable certain codes for booking?

**Comment by ianhinder** [comment]
Would it make sense to restrict the list of available codes to book against to those for which you have been assigned to the corresponding project?

**Comment by aharwood2** [comment]
We could, Ian, but you never know when someone might need to book to another code for work "outside their formal assignment" so I don't want to be too restrictive. I think just turning off legacy codes might be useful but it is another thing to maintain I guess. It was the same in Innate and I had to ask people every now and then "can I disable this code".

**Comment by aharwood2** [comment]
Simplest way to do this is to add a bool to the Innate code model so we can turn it off.
